import random
rg = random.randint(1, 100)

q = 1
count = 0
print("let's guess the number which your machine has generated...!!!")
while q:
    p = int(input("enter a number: "))
    count += 1
    if p > rg:
        print("you guessed it wrong..!enter a smaller number: ")
    elif p < rg:
        print("you guessed it wrong..!enter a greater number: ")
    else:
        q = 0
print("hurray...!your number matched..!")
print(f"The random number generated by your machine is: {rg}")
print(f"The number of attempts you've taken to guess the number is:{count}")
with open("hiscore.txt", "r")as f:
    sc = int(f.read())

if count < sc:
    print("you've just broken the existing record")
    with open("hiscore.txt", "w")as f:
        f.write(str(count))
